FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip git curl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# nnU-Net paths (PADRÃO)
ENV nnUNet_results=/app/nnUNet_results
ENV nnUNet_raw=/app/nnUNet_raw
ENV nnUNet_preprocessed=/app/nnUNet_preprocessed

RUN mkdir -p /app/nnUNet_results /app/nnUNet_raw /app/nnUNet_preprocessed /app/data/input /app/data/output

# Copia modelos PARA nnUNet_results
COPY models/ /app/nnUNet_results/

# Copia código
COPY handler.py infer_umamba.py ./

CMD ["python3", "handler.py"]
