FROM nvidia/cuda:12.1.1-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 python3-pip wget unzip \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY handler.py .
COPY infer_umamba.py .
COPY download_models.py .

ENV nnUNet_results=/app/models/nnUNet_results

RUN python3 download_models.py

CMD ["python3", "handler.py"]
